name: Aggiornamento SuperEnalotto su Kaggle

on:
  push:
    branches:
      - main  # Esegui quando viene fatto push sul ramo 'main'
  schedule:
    - cron: "0 0 * * *"  # Esegui ogni giorno a mezzanotte (UTC)

jobs:
  update_dataset:
    runs-on: ubuntu-latest
    env:
      # Rende disponibile il secret a *tutti* i passi del job
      KAGGLE_JSON: ${{ secrets.KAGGLE_JSON }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

          # Step 3: Installa le dipendenze
      - name: Installa le dipendenze
        run: |
         python -m pip install --upgrade pip
         pip install pandas requests beautifulsoup4 kaggle lxml html5lib

      - name: Crea la cartella .kaggle e salva kaggle.json
        run: |
          mkdir -p ~/.kaggle
          echo "$KAGGLE_JSON" > ~/.kaggle/kaggle.json
          chmod 600 ~/.kaggle/kaggle.json

      - name: Esegui lo script Python
        run: python main.py
