name: Aggiornamento SuperEnalotto su Kaggle

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 0 * * *"  # Ogni giorno a mezzanotte UTC

jobs:
  update_dataset:
    runs-on: ubuntu-latest
    env:
      KAGGLE_JSON: ${{ secrets.KAGGLE_JSON }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Installa dipendenze
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests beautifulsoup4 kaggle lxml html5lib

      - name: Configura Kaggle credentials
        run: |
          mkdir -p ~/.kaggle
          echo "$KAGGLE_JSON" > ~/.kaggle/kaggle.json
          chmod 600 ~/.kaggle/kaggle.json

      - name: Verifica presenza e contenuto di kaggle.json  # debug
        run: |
          ls -l ~/.kaggle/kaggle.json
          sed -E 's/"key"\s*:\s*"[A-Za-z0-9]+"/"key":"****"/' ~/.kaggle/kaggle.json

      - name: Esegui lo script di aggiornamento
        run: python main.py
