name: Aggiornamento SuperEnalotto su Kaggle

on:
  push:
    branches:
      - main        # Trigger su push al ramo main
  schedule:
    - cron: "0 0 * * *"  # Esegue ogni giorno a mezzanotte UTC

jobs:
  update_dataset:
    runs-on: ubuntu-latest

    # Rende disponibile il secret KAGGLE_JSON a tutti gli step
    env:
      KAGGLE_JSON: ${{ secrets.KAGGLE_JSON }}

    steps:
      # 1) Clona il repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2) Imposta Python 3.10
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # 3) Installa le dipendenze (inclusi lxml e html5lib per pd.read_html)
      - name: Installa dipendenze
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests beautifulsoup4 kaggle lxml html5lib

      # 4) Crea ~/.kaggle e salva il file kaggle.json dal secret
      - name: Configura Kaggle credentials
        run: |
          mkdir -p ~/.kaggle
          echo "$KAGGLE_JSON" > ~/.kaggle/kaggle.json
          chmod 600 ~/.kaggle/kaggle.json

      # 5) DEBUG: verifica contenuto parziale di kaggle.json
      - name: Debug: mostra la chiave username
        run: |
          echo "---- START kaggle.json ----"
          sed -E 's/"key"[[:space:]]*:[[:space:]]*"[A-Za-z0-9]+"/"key":"****"/' ~/.kaggle/kaggle.json
          echo "---- END kaggle.json ----"

      # 6) Esegui lo script Python
      - name: Esegui lo script di aggiornamento
        run: python main.py
